OUTPUT_DIR = "output"
TRAINING_DIR = "training"
VALIDATION_DIR = "validation"
ENCODINGS_DIR = "encodings"

REQUIRED_DIRS = (OUTPUT_DIR, TRAINING_DIR, VALIDATION_DIR, ENCODINGS_DIR)

UNKNOWN = "unknown"
EXIF_DATETIME_ORIGINAL_TAG = 36867
EXIF_DATETIME_MODIFIED_TAG = 306
